### ISSUE TITLE
BUGS: Android Smart TV (Sony Bravia)

### ISSUE THREAD

**Issue by f-o** [yuliskov/SmartYouTubeTV#307]
I've finally decided to create my own issue, instead of piggy-back-riding off of other peoples topics.

Here are a couple of issues with the newest release (6.17.27) on my Sony Bravia Android Smart TV.

### 1) No possibility to add videos to playlist
When you open the Playlist adder, it will immediately shut down, without giving you the option to add.
Even if you press right as it opens, it wont add a video.
Here's a small video of the issue in question: https://drive.google.com/open?id=1Yma_IaibFnhoQb5at3tB731JC-t-NKJw

### 2) Video recommendations not showing up
When you click on the recommended videos tab, some grey boxes will pop up, and you will not be able to enter the category at all.
Here's a small video of the issue in question: https://drive.google.com/open?id=1Dj1imDmSh5U5cURc5a-rosUxvVOznqV5

### 3) Constant stop of playback for Loading...
This one is probably the most annoying of the bunch, and we've tried to solve it before, but I hope you will give it another shot, as you can tell by the video it is extremely annoying, and renders the entire app useless to be honest.
When you start _some_ videos (it is not all, and there seems to be no indication of which kind of videos) the playback will show a long initial "Loading.." screen, and afterwards the video will continuously stop and buffer.
It has nothing to do with the uplink, as my television is directly connected via cable to a 300mbit router.
In the video, I even tried to lower the resolution, and it still gave the loading-error.
Here's a small video: https://drive.google.com/open?id=1-P42AXQWRoJjhob45EbgW474adUktcoG

Here is a combined log for all of the events: 
[log (6).txt](https://github.com/yuliskov/SmartYouTubeTV/files/3364669/log.6.txt)
Issue 1: 13:52
Issue 2: 13:54
Issue 3: 13:55

Again, thank you for developing this app, which has always been my absolutely most beloved application for my television.
I'm hoping we can solve these issues together. 
If you need me to test anything, let me know.

**Comment by yuliskov** [comment]
Thanks. I've released new build. Some of this issues should be fixed there.

2019-07-06 15:30 GMT+03:00, f-o <notifications@github.com>:

**Comment by f-o** [comment]
You're right.
The 1st and 2nd issue has seem to be resolved. 

However, when testing I found something odd. 

If you add a video to "Watch later", it will say that it's been added, but if you then go into Library->Watch Later, it will list all the videos from "My videos" instead.
All other play lists seems to be working as intended. 

Regarding the loading issue, have you looked at this in the newest release (17.32)?
I just did ~10 videos playback, and it didn't seem to come up, but as stated it is very random when this issue appears.

**Comment by f-o** [comment]
I take that back.
Upon playing the 11th video, the issue appeared once again.. 

Here's a log. 
The video with the Loading.. issue started playing at 15:03
[log (7).txt](https://github.com/yuliskov/SmartYouTubeTV/files/3364697/log.7.txt)

**Comment by ok5266** [comment]
I have updated to 6.17.34, but the problems still exist. The videos and programs excerpt live streams can not be played. Sometimes, just a image shows on the screen.

**Comment by ghost** [comment]
> I've finally decided to create my own issue, instead of piggy-back-riding off of other peoples topics.
> 
> Here are a couple of issues with the newest release (6.17.27) on my Sony Bravia Android Smart TV.
> 
> ### 1) No possibility to add videos to playlist
> When you open the Playlist adder, it will immediately shut down, without giving you the option to add.
> Even if you press right as it opens, it wont add a video.
> Here's a small video of the issue in question: https://drive.google.com/open?id=1Yma_IaibFnhoQb5at3tB731JC-t-NKJw
> 
> ### 2) Video recommendations not showing up
> When you click on the recommended videos tab, some grey boxes will pop up, and you will not be able to enter the category at all.
> Here's a small video of the issue in question: https://drive.google.com/open?id=1Dj1imDmSh5U5cURc5a-rosUxvVOznqV5
> 
> ### 3) Constant stop of playback for Loading...
> This one is probably the most annoying of the bunch, and we've tried to solve it before, but I hope you will give it another shot, as you can tell by the video it is extremely annoying, and renders the entire app useless to be honest.
> When you start _some_ videos (it is not all, and there seems to be no indication of which kind of videos) the playback will show a long initial "Loading.." screen, and afterwards the video will continuously stop and buffer.
> It has nothing to do with the uplink, as my television is directly connected via cable to a 300mbit router.
> In the video, I even tried to lower the resolution, and it still gave the loading-error.
> Here's a small video: https://drive.google.com/open?id=1-P42AXQWRoJjhob45EbgW474adUktcoG
> 
> Here is a combined log for all of the events:
> [log (6).txt](https://github.com/yuliskov/SmartYouTubeTV/files/3364669/log.6.txt)
> Issue 1: 13:52
> Issue 2: 13:54
> Issue 3: 13:55
> 
> Again, thank you for developing this app, which has always been my absolutely most beloved application for my television.
> I'm hoping we can solve these issues together.
> If you need me to test anything, let me know.


@f-o  I am having the same loading issue with this app on all versions. As of September 9, 2019. Was it resolved on your end? 

@yuliskov This is the exact issue I mentioned having regards to loading videos on app but I'm on Firestick.

**Comment by f-o** [comment]
> @f-o I am having the same loading issue with this app on all versions. As of September 9, 2019. Was it resolved on your end?

I'm afraid the issue was not resolved, unfortunately.
Yuliskov and I had some back-and-forward messages, testing new versions of the app, but ultimately a solution wasn't found.

Shortly after, a new update was released, where the "Loading..."-text was changed to a spinning circle.
Brought back some patience when waiting, I guess.


That being said, I must admit that the problem has become way less frequent.
Previously, every second video would throw the error of a constant loading-screen, but now it's more like every 10th video.
Still, it's extremely annoying, as the videos will not be playable at all, not even after closing the video and opening again, so the only thing to do is to find something else to watch.

**Comment by yuliskov** [comment]
@f-o hi, thanks for your help. I propose you to gather the log and post it here.
Log is enabled this way. Go to the launcher select screen. Then click on Tweaks. List with options should pop-up. Select 'Save log to the file' from here.
latest beta:
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.17.106/SYTV_Orig_v6.17.106_r.apk

**Comment by ghost** [comment]
@f-o I'm having the loading problems regardless of any video I am trying to play on the app. Its really bad like every 5 seconds for the most part. In addition to the casting problem where after putting in the code after closing app and re-opening it I cant cast to tv anymore. Smart Youtube TV is practically unusable. I have none of these such issues on the regular Youtube app. Except with it I get ads and jittery video playback at times. 

@yuliskov Do you want me to post log here? I dont think I have the newest app release I'll have to try it out.  Yeah i'm on 6.17.91 I will update app.

**Comment by yuliskov** [comment]
@JRK84 log would be good. But, before that, describe your issues more deeply. Videos not playing at all?

**Comment by ghost** [comment]
> @JRK84 log would be good. But, before that, describe your issues more deeply. Videos not playing at all?

Sorry I just updated to 6.17.106. On 91 I am having issues with all videos loading once started. They stop every 5 seconds and I get the circle loading symbol. I press pause and wait like several minutes then play again and so on. As for casting I put in the tv code to cast from youtube on computer to smartyoutube tv app and it works the first time I put the code in. But after I close the app and re-open it then it no longer will cast to firestick and Youtube TV is not listed just my firestick which does nothing. Let me see how this update does now. I marked logs to save but how do I extract the files from the firestick to post on here?

**Comment by ghost** [comment]
@yuliskov Ok after playing a video on the new app update it looks like the casting feature works after putting in tv code playing a video from computer then exit app re-open it and go back onto my youtube account on computer and im able to cast again to tv.

The loading issue still is a big problem. within 3 minutes of the video it has stopped at least 3 times.

How do I send you the log from my firestick?

**Comment by ghost** [comment]
@yuliskov Here is the log 
[log.txt](https://github.com/yuliskov/SmartYouTubeTV/files/3607555/log.txt)

**Comment by ghost** [comment]
@yuliskov Have you been able to look at the log and do you have a fix? Also the casting problem is back.
